services:
  bdd:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: pointage_demande_conge
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "ProjetDotNet!123"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqlserver_data:
